In [10]:
import numpy as np

l1 = [[1,2,3,0],
      [11,22,-3,0],
      [-1,-2,4,0]]

a1 = np.array(l1)


In [17]:
a1.shape

(3, 4)

In [24]:
for x in a1:
    print(x)
    print(type(x))

[1 2 3 0]
<class 'numpy.ndarray'>
[11 22 -3  0]
<class 'numpy.ndarray'>
[-1 -2  4  0]
<class 'numpy.ndarray'>


In [22]:
np.random.uniform(0,1,(2,3))

array([[0.47966905, 0.89860282, 0.33134211],
       [0.60958879, 0.41598354, 0.54151927]])

In [28]:
np.inf < 100

False